CREATE DATABASE IF NOT EXISTS jgenkzym;
CREATE DATABASE IF NOT EXISTS wje4rmtr;
CREATE DATABASE IF NOT EXISTS zn62jyyu;
CREATE DATABASE IF NOT EXISTS 2wdx6yex;
CREATE DATABASE IF NOT EXISTS 5ubuuepk;
CREATE DATABASE IF NOT EXISTS r2z4hbn7;


CREATE USER 'jgenkzym'@'%' IDENTIFIED BY 'K7QhhFz7';
CREATE USER 'wje4rmtr'@'%' IDENTIFIED BY 'BK6Xnruq';
CREATE USER 'zn62jyyu'@'%' IDENTIFIED BY 'Z98KmycL';
CREATE USER '2wdx6yex'@'%' IDENTIFIED BY 'mZNJLPDP';
CREATE USER '5ubuuepk'@'%' IDENTIFIED BY 'kndSqTwc';
CREATE USER 'r2z4hbn7'@'%' IDENTIFIED BY 'MhDpQmEp';

GRANT ALL PRIVILEGES ON jgenkzym.* TO 'jgenkzym'@'%';
GRANT ALL PRIVILEGES ON wje4rmtr.* TO 'wje4rmtr'@'%';
GRANT ALL PRIVILEGES ON zn62jyyu.* TO 'zn62jyyu'@'%';
GRANT ALL PRIVILEGES ON 2wdx6yex.* TO '2wdx6yex'@'%';
GRANT ALL PRIVILEGES ON 5ubuuepk.* TO '5ubuuepk'@'%';
GRANT ALL PRIVILEGES ON r2z4hbn7.* TO 'r2z4hbn7'@'%';